services:
  web:
    container_name: web-app-appnew-jenkins-3
    hostname: app
    build: .
    ports:
      - "0.0.0.0:5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
